const motivationalPhrases = [
    "Let it be,",
    "Stay inspired, ",
    "Dream big, ",
    "Shine on, ",
    "Forge ahead, ",
    "Create magic, ",
    "Embrace change, ",
    "Unleash greatness, ",
    "Lead with passion, ",
    "Rise and thrive, ",
    "Ignite possibilities, ",
    "Craft your story, ",
    "Inspire and conquer, ",
    "Empower your journey, ",
    "Chase dreams fearlessly, ",
    "Write your legacy, ",
    "Inspire and ascend, ",
    "Elevate with purpose, ",
    "Shape the world, ",
    "Design your destiny, ",
    "Stay curious, ",
    "Dream boldly, ",
    "Rise to challenges, ",
    "Inspire innovation, ",
    "Champion of change, ",
    "Ignite your fire, ",
    "Lead with heart, ",
    "Fearless explorer, ",
    "Create impact, ",
    "Embrace growth, ",
    "Unleash potential, ",
    "Lead by example, ",
    "Shine brightly, ",
    "Trailblaze with purpose, ",
    "Dream and achieve, ",
    "Inspire progress, ",
    "Fearless dreamer, ",
    "Create your legacy, ",
    "Embrace possibilities, ",
    "Unleash creativity, ",
    "Lead with authenticity, ",
    "Ignite positive change, ",
    "Shape your destiny, ",
    "Inspire forward motion, ",
    "Champion of innovation, ",
    "Dream, create, conquer, ",
    "Embrace the extraordinary, ",
    "Lead with purposeful intent, ",
    "Inspire brilliance, ",
    "Elevate your journey, ",
    "Lead with resilience, ",
    "Chase dreams relentlessly, ",
    "Fuel your passions, ",
    "Spark creativity, ",
    "Inspire, innovate, impact, ",
    "Dream big, shine brighter, ",
    "Ignite your potential, ",
    "Craft your success story, ",
    "Trailblaze with purpose, ",
    "Shape a remarkable legacy, ",
    "Dream, believe, achieve, ",
    "Empower your uniqueness, ",
    "Radiate positivity, ",
    "Lead boldly, ",
    "Inspire and transcend, ",
    "Champion your aspirations, ",
    "Fearlessly embrace challenges, ",
    "Ignite the spark of change, ",
    "Elevate with determination, ",
    "Shape your destiny, ",
    "Inspire others to greatness, ",
    "Dream and conquer, ",
    "Lead with unwavering purpose, ",
    "Embrace the unknown, ",
    "Inspire progress daily, ",
    "Champion of boundless possibilities, ",
    "Fearlessly explore, ",
    "Ignite the fire within, ",
    "Elevate your impact, ",
    "Lead by example, ",
    "Inspire with authenticity, ",
    "Dream big, impact bigger, ",
    "Fearless pursuit of excellence, ",
    "Ignite change, ",
    "Elevate your potential, ",
    "Lead with purpose, ",
    "Inspire and empower, ",
    "Dreams realized, ",
    "Fearless in pursuit, ",
    "Ignite innovation, ",
    "Elevate your passion, ",
    "Lead with determination, ",
    "Inspire boundless curiosity, ",
    "Dream, conquer, thrive, ",
    "Fearlessly embrace challenges, ",
    "Ignite brilliance, ",
    "Elevate with enthusiasm, ",
    "Lead the way, ",
    "Inspire change, ",
    "Shine like the stars,",
    "Unleash your inner strength, ",
    "Strive for greatness, ",
    "Create your own path, ",
    "Embrace the journey, ",
    "Lead with courage, ",
    "Dream without limits, ",
    "Level up your skills, ",
    "Conquer challenges like a pro, ",
    "Game on with determination, ",
    "Master your craft, ",
    "Strategize for success, ",
    "Embrace the grind, ",
    "Victory through perseverance, ",
    "Rise to the gaming throne, ",
    "Fuel your passion for gaming, ",
    "Unleash your gaming potential, ",
    "Dominate the virtual world, ",
    "Embrace every game as a challenge, ",
    "Stay sharp, stay victorious, ",
    "Game with heart and soul, ",
    "Level by level, you rise, ",
    "Defy limitations, conquer games, ",
    "Gameplay with purpose, ",
    "Every loss is a lesson, ",
    "Game hard, game smart, ",
    "Your journey, your game, ",
    "Embrace the gaming adventure, ",
    "Chase the win, ",
    "Skills unlocked, dynamo mode on!",
    "Gaming is your canvas, ",
    "Mastermind of gaming strategy, ",
    "Passion for gaming, ",
    "Resilience in the face of challenges, ",
    "Every move matters, ",
    "Level up, thrive, ",
    "Gaming excellence, your destiny, ",
    "Conquer, create, compete, ",
    "Challenge accepted, ",
    "Victory is your legacy, ",
    "Gameplay with passion, ",
    "Unleash the gamer within, ",
    "Rise to the leaderboard, ",
    "Forge your gaming legend, ",
    "Level up your potential, ",
    "Game with determination, ",
    "Gaming journey, endless horizons, ",
    "Skillset, strategy, success, ",
    "Master the game, ",
    "Defeat is not an option, ",
    "Gameplay fueled by ambition, ",
    "Rise above, game on, ",
    "Gaming goals, dynamo mode activated!",
    "Embrace the virtual battlefield, ",
    "Chase victory with heart, ",
    "Your skills, your destiny, ",
    "Unleash the gamer spirit, ",
    "Victory through skill and strategy, ",
    "Gameplay that sets you apart, ",
    "Level up your game, ",
    "Conquer, compete, excel, ",
    "Ignite your passion,  ",
    "Spark positive change,  ",
    "Elevate with perseverance,  ",
    "Shape your destiny,  ",
    "Inspire and conquer,  ",
    "Believe in the extraordinary,  ",
    "Empower your dreams,  ",
    "Radiate positivity,  ",
    "Lead boldly and inspire,  ",
    "Champion of innovation,  ",
    "Embrace challenges with grace,  ",
    "Unleash your limitless potential,  ",
    "Rise above,  ",
    "Create your legacy,  ",
    "Inspire with authenticity,  ",
    "Craft your own success story,  ",
    "Be the change,  ",
    "Fuel your ambitions,  ",
    "Shine brighter than before,  ",
    "Lead by example,  ",
    "Chase your dreams,  ",
    "Ignite your creativity,  ",
    "Elevate with determination,  ",
    "Shape the future,  ",
    "Believe in the impossible,  ",
    "Empower your journey,  ",
    "Radiate confidence,  ",
    "Lead with purpose,  ",
    "Inspire transformation,  ",
    "Spark innovation,  ",
    "Embrace every challenge,  ",
    "Unleash your potential,  ",
    "Rise and conquer,  ",
    "Dream big and bold,  ",
    "Champion of your aspirations,  ",
    "Empower your vision,  ",
    "Shine as a beacon,  ",
    "Inspire progress daily,  ",
    "Lead with resilience,  ",
    "Embrace your uniqueness,  ",
    "Craft your own destiny,  ",
    "Fuel your passions with fire,  ",
    "Ignite change from within,",
    "Elevate your goals,",
    "Shape the world around you,",
    "Elevate your aesthetic vision, ",
    "Craft beauty with intention, ",
    "Chase aesthetics with passion, ",
    "Design your world, ",
    "Embrace the elegance within, ",
    "Create art in every detail, ",
    "Curate life's beauty, ",
    "Shape your surroundings, ",
    "Harmonize aesthetics with purpose, ",
    "Envision, create, inspire, ",
    "Compose your aesthetic masterpiece, ",
    "Let your creativity flourish, ",
    "Every detail matters, ",
    "Embrace aesthetics as a lifestyle, ",
    "Design with heart and soul, ",
    "Cherish the beauty around you, ",
    "Craft elegance, ",
    "Curate your aesthetic identity, ",
    "Embrace the artistry of life, ",
    "Create your visual symphony, ",
    "Harmonize aesthetics with authenticity, ",
    "Shape the world with your aesthetic touch, ",
    "Envision beauty, bring it to life, ",
    "Compose your aesthetic narrative, ",
    "Let your style radiate, ",
    "Every moment, an aesthetic opportunity, ",
    "Embrace aesthetics, let it speak, ",
    "Design your reality, ",
    "Cherish the art of simplicity, ",
    "Craft your aesthetic masterpiece, ",
    "Curate the beauty within, ",
    "Embrace the elegance of expression, ",
    "Create visuals that resonate, ",
    "Harmonize aesthetics with emotion, ",
    "Shape your aesthetic destiny, ",
    "Envision beauty, inspire awe, ",
    "Compose life's aesthetic tapestry, ",
    "Let aesthetics flow through you, ",
    "Every touch, an aesthetic stroke, ",
    "Embrace the art of living beautifully, ",
    "Design a world of aesthetics, ",
    "Cherish the aesthetic journey, ",
    "Craft aesthetics that inspire, ",
    "Curate beauty in every corner, ",
    "Embrace the magic of aesthetics, ",
    "Create visuals that captivate, ",
    "Harmonize aesthetics with elegance, ",
    "Shape your aesthetic realm, ",
    "Envision, create, enchant, ",
    "Compose your aesthetic story, ",
    "Let aesthetics define your world, ",
    "Dominate the streets, ",
    "Rise as a criminal kingpin, ",
    "Master chaos and conquer, ",
    "Navigate the virtual underworld, ",
    "Drive fast, live faster, ",
    "Embrace the criminal mastermind within, ",
    "Level up and own the city, ",
    "Write your own crime saga, ",
    "Chase the thrill of heists, ",
    "Rule the virtual criminal empire, ",
    "Live on the edge of chaos, ",
    "Be the legend of the underworld, ",
    "Navigate the concrete jungle, ",
    "Conquer the digital city, ",
    "Steer through danger and triumph, ",
    "Unleash mayhem with style, ",
    "Embrace the life of crime, ",
    "Mastermind heists like a pro, ",
    "Rise from rags to criminal riches, ",
    "Drive hard, play harder, ",
    "Embody the spirit of a virtual outlaw, ",
    "Dominate the game with cunning, ",
    "Live by your own rules, ",
    "Conquer the virtual streets, ",
    "Chase the adrenaline, ",
    "Rule the underworld with strategy, ",
    "Navigate the realm of crime, ",
    "Rise to the top as a criminal legend, ",
    "Master the art of virtual chaos, ",
    "Drive, steal, repeat, ",
    "Embrace the criminal lifestyle, ",
    "Lead heists with precision, ",
    "Conquer the city with style, ",
    "Steer through danger and success, ",
    "Unleash destruction and triumph, ",
    "Embody the essence of an outlaw, ",
    "Dominate the digital realm, ",
    "Live life on the edge, ",
    "Rule the underworld with cunning, ",
    "Chase the thrill of virtual crime, ",
    "Mastermind heists like a legend, ",
    "Rise from anonymity to infamy, ",
    "Drive fast, loot faster, ",
    "Embrace the world of crime, ",
    "Conquer the game's challenges, ",
    "Steer through chaos and emerge victorious, ",
    "Unleash your inner outlaw, ",
    "Embody the spirit of a virtual gangster, ",
    "Dominate the urban landscape, ",
    "Live the life of a digital criminal, ",
    "Embrace your individuality, ",
    "Walk your own path, ",
    "Quiet strength is your power, ",
    "Lead with silent confidence, ",
    "Navigate life on your terms, ",
    "Embrace solitude, thrive in silence, ",
    "Master the art of independence, ",
    "Chase success on your own terms, ",
    "Rise above the noise, ",
    "Be the architect of your destiny, ",
    "Unleash your unique perspective, ",
    "Live with purpose and authenticity, ",
    "Embody self-reliance and wisdom, ",
    "Quietly conquer challenges, ",
    "Navigate challenges with resilience, ",
    "Embrace the role of an observer, ",
    "Lead with unspoken influence, ",
    "Master the balance of self and society, ",
    "Chase growth through introspection, ",
    "Rise to greatness with quiet determination, ",
    "Be the enigma that inspires change, ",
    "Unleash your potential beyond expectations, ",
    "Embrace your inner strength, ",
    "Live with unwavering authenticity, ",
    "Embody inner peace and serenity, ",
    "Quietly shape your own reality, ",
    "Navigate life's complexities with finesse, ",
    "Lead by example, not by volume, ",
    "Master the art of meaningful connections, ",
    "Chase your goals with focused intent, ",
    "Rise above conformity, ",
    "Be the understated force of change, ",
    "Unleash your resilience and adaptability, ",
    "Embrace the mystery of your potential, ",
    "Live with purposeful detachment, ",
    "Embody the strength of independence, ",
    "Quietly conquer self-doubt, ",
    "Navigate challenges with calculated precision, ",
    "Lead through actions, not words, ",
    "Master your emotions, ",
    "Chase excellence on your own timeline, ",
    "Rise to leadership with authenticity, ",
    "Be the master of your own narrative, ",
    "Unleash your potential without fanfare, ",
    "Embrace your inner solitude, ",
    "Live in alignment with your values, ",
    "Embody the essence of self-discovery, ",
    "Navigate life with self-assuredness, ",
    "Lead with quiet authority, ",
    "Master the art of introspection, ",
    "Your journey is worth fighting for, ",
    "Every small step is a victory, ",
    "Embrace self-care as a daily ritual, ",
    "Reach out for help, you're not alone, ",
    "Strength comes from facing your challenges, ",
    "Your story is not defined by your struggles, ",
    "Tomorrow is a new opportunity, ",
    "Find beauty in small moments, ",
    "Your feelings are valid, ",
    "Let self-compassion guide you, ",
    "Lean on others for support, ",
    "Your resilience is inspiring, ",
    "Seek joy in simple pleasures, ",
    "Practice patience with yourself, ",
    "Recovery is a journey, not a destination, ",
    "Believe in your inner strength, ",
    "Small progress is still progress, ",
    "Take things one step at a time, ",
    "Cherish the good days, ",
    "Your worth is not defined by productivity, ",
    "Rest and self-care are powerful, ",
    "Let hope be your guiding light, ",
    "Embrace self-love as a healing force, ",
    "Reach out to someone you trust, ",
    "Remember, you're not alone in this, ",
    "Focus on the present moment, ",
    "Every sunrise brings a new beginning, ",
    "Your resilience will guide you through, ",
    "Practice self-compassion, ",
    "Even in darkness, you have inner strength, ",
    "Seek support from those who care, ",
    "Believe in your ability to heal, ",
    "Small victories add up, ",
    "Embrace self-kindness as a lifeline, ",
    "Your journey is unique and valuable, ",
    "Recovery takes time, and that's okay, ",
    "Find comfort in the presence of loved ones, ",
    "Your feelings matter, ",
    "Hope is a powerful force, ",
    "Embrace self-discovery as a path forward, ",
    "Reach out for professional help, ",
    "Believe in your capacity for growth, ",
    "Your strength shines even on tough days, ",
    "Find solace in nature's beauty, ",
    "Your struggles don't define your worth, ",
    "Recovery is a journey worth taking, ",
    "Even small steps are worth celebrating, ",
    "Your story is still being written, ",
    "Embrace self-acceptance as a starting point, ",
    "Lean on positive memories, ",
    "Believe in the power of healing, ",
    "Code with passion, ",
    "Debugging is a journey to excellence, ",
    "Every line of code is a step forward, ",
    "Embrace challenges as coding puzzles, ",
    "Continuous learning fuels innovation, ",
    "Your code shapes the digital world, ",
    "Perseverance leads to elegant solutions, ",
    "Craft clean code like an artist, ",
    "Think algorithmically, code strategically, ",
    "Strive for efficiency in every line, ",
    "Debugging is a detective adventure, ",
    "Code is your canvas, creativity is your brush, ",
    "Embrace the power of collaboration, ",
    "Code fuels progress and innovation, ",
    "Every bug fixed is a victory, ",
    "Challenge yourself to refactor and improve, ",
    "Programming is a journey of constant growth, ",
    "Coding is a language that speaks innovation, ",
    "Commit to excellence in every commit, ",
    "Embrace the beauty of elegant code, ",
    "Logic and creativity converge in coding, ",,
    "Debugging refines your coding skills, ",
    "Code transforms ideas into reality, ",
    "Cherish the satisfaction of a well-structured program, ",
    "Challenge yourself to explore new frameworks, ",
    "Commit to continuous improvement, ",
    "Embrace the debugging process as a learning opportunity, ",
    "Coding is the art of logic and imagination, ",
    "Code is your tool to shape digital landscapes, ",
    "Strive for optimal performance in every line, ",
    "Every codebase tells a story of innovation, ",
    "Code with intention, create with purpose, ",
    "Embrace the intricacies of coding challenges, ",
    "Continuous integration, continuous improvement, ",
    "Your code leaves a lasting impact, ",
    "Programming is the bridge between imagination and reality, ",
    "Challenge yourself to master new languages, ",
    "Code is a reflection of your problem-solving skills, ",
    "Debugging sharpens your coding expertise, ",
    "Coding is an ever-evolving art, ",
    "Embrace the joy of problem-solving, ",
    "Logic guides your code, creativity shapes it, ",
    "Programming is the language of innovation, ",
    "Cherish the elegance of optimized code, ",
    "Commit to writing code that inspires, ",
    "Embrace the iterative nature of development, ",
    "Coding is the rhythm of progress, ",
    "Challenge yourself to tackle complex algorithms, ",
    "Code is the architecture of digital dreams, ",
    "Logic and creativity harmonize in coding, ",
    "Debugging reveals the path to perfection, ",
    "Programming is the heartbeat of technological advancement, ",
    "Embrace the thrill of creating functional art, ",
    "Strength is found in embracing vulnerability, ",
    "Every setback is a stepping stone to resilience, ",
    "Courage shines brightest in moments of adversity, ",
    "Embrace your struggles as opportunities for growth, ",
    "Even the smallest steps lead to greater strength, ",
    "Your journey is a testament to your inner fortitude, ",
    "Rise from weakness to inspire others, ",
    "Challenges are your platform for transformation, ",
    "From weakness comes the courage to conquer, ",
    "Embrace the process of building inner strength, ",
    "Your journey shapes you into a stronger version, ",
    "Turn your struggles into stepping stones, ",
    "Embrace your weaknesses as a canvas for growth, ",
    "Your story is one of resilience and strength, ",
    "Transform vulnerability into a wellspring of power, ",
    "Embrace your challenges, for they shape your strength, ",
    "Your journey through weakness reveals your true power, ",
    "From adversity springs the strength to thrive, ",
    "Embrace your struggles as a testament to your strength, ",
    "Rise from the ashes of weakness, stronger than before, ",
    "Your courage in weakness becomes your strength, ",
    "Turn your challenges into fuel for inner growth, ",
    "Embrace your imperfections as the foundation of your strength, ",
    "From vulnerability emerges unwavering strength, ",
    "Your journey through weakness is a testament to your strength, ",
    "Rise above your weaknesses, embrace your strength, ",
    "Transform challenges into opportunities for resilience, ",
    "Your journey reflects your inner strength, ",
    "Embrace your weaknesses as the foundation of your strength, ",
    "Turn adversity into a catalyst for growth, ",
    "From struggle arises the strength to conquer, ",
    "Your story is one of triumph over weakness, ",
    "Transform vulnerability into unwavering strength, ",
    "Embrace your challenges as a chance to rise, ",
    "Rise from weakness with newfound strength, ",
    "Turn your battles into victories of resilience, ",
    "From obstacles emerges the strength to overcome, ",
    "Embrace your journey through weakness as a source of strength, ",
    "Your struggles become the building blocks of your strength, ",
    "Transform vulnerability into a force of empowerment, ",
    "Embrace your challenges as opportunities for strength, ",
    "Rise from adversity with a heart full of strength, ",
    "From weakness blooms the strength to endure, ",
    "Embrace your struggles as a wellspring of inner strength, ",
    "Your journey through weakness is your path to strength, ",
    "Turn vulnerability into a testament of your strength, ",
    "Embrace your challenges as the path to greater strength, ",
    "Rise above weakness, for strength resides within, ",
    "Transform adversity into a journey of strength, ",
    "Embrace your struggles, for they reveal your inner strength, ",
    "Your journey through weakness unveils your true power, ",
    "Turn challenges into stepping stones of resilience, ",
    "From vulnerability comes the strength to conquer, ",
    "Locked and loaded, ready to conquer, ",
    "Aim high, shoot higher, ",
    "Precision and focus pave the way to victory, ",
    "Channel your inner marksman, ",
    "Stay steady, shoot steady, ",
    "From cover to victory, ",
    "Your accuracy sets the battlefield ablaze, ",
    "Every shot counts, make them legendary, ",
    "Embrace the chaos, emerge victorious, ",
    "Your aim shapes the battleground, ",
    "Locked on target, success is in sight, ",
    "Bullet by bullet, you rewrite the battlefield, ",
    "Reload, recalibrate, and rise, ",
    "Precision is your weapon, dominance is your goal, ",
    "Turn every shot into a masterpiece, ",
    "From sniper to champion, your shots define you, ",
    "Firepower and strategy: your keys to triumph, ",
    "Your bullets paint victory across the battlefield, ",
    "Master the trigger, control the outcome, ",
    "Amidst gunfire, your aim stands unshaken, ",
    "Lock, load, and leave your mark, ",
    "Reload, reposition, and reign supreme, ",
    "Your aim is your compass in the chaos, ",
    "Shoot for glory, shoot for triumph, ",
    "In the crosshairs of victory, you stand tall, ",
    "Precision, patience, and power: your ultimate arsenal, ",
    "Each shot fuels your path to dominance, ",
    "Sharpshooter's eye, champion's heart, ",
    "From gunplay to gameplay, you excel, ",
    "Your shots resonate with victory, ",
    "Reload with confidence, victory awaits, ",
    "Each bullet carries the weight of your ambition, ",
    "Your aim turns battles into triumphs, ",
    "Unleash your accuracy, unleash your reign, ",
    "Every bullet fired is a step towards victory, ",
    "Your precision strikes fear into your rivals, ",
    "Target acquired, success assured, ",
    "From reload to retribution, you dominate, ",
    "Precision is your tool, victory is your reward, ",
    "Each shot is a brushstroke on the canvas of victory, ",
    "Your aim shapes the outcome, ",
    "Reload, recalibrate, and rise to greatness, ",
    "From muzzle flash to victory dance, you're the star, ",
    "Each shot fired is a step towards glory, ",
    "Your accuracy is your ticket to supremacy, ",
    "In the heat of battle, your aim remains true, ",
    "Reload and rise above, champion of the gunfight, ",
    "Your accuracy is a force to be reckoned with, ",
    "From sights aligned to victory defined, ",
    "Every bullet fired is a declaration of dominance, ",
    "Your precision sets the stage for triumph, ",
    "Reload and rewrite the rules of engagement, ",
    "Your shots echo with the sound of victory, ",
    "Rev up your passion, conquer the track, ",
    "Every turn is a chance to shine, ",
    "From zero to hero, let your wheels do the talking, ",
    "Navigate the asphalt like a maestro, ",
    "Pedal to the metal, heart in the game, ",
    "Roaring engines, unyielding determination, ",
    "Master of the road, you leave your rivals in the dust, ",
    "Embrace the speedway and leave your mark, ",
    "Fuel your dreams, power through the circuit, ",
    "Life's a race, and you're the fearless driver, ",
    "From gear shifts to glory, you lead the pack, ",
    "Navigate the twists and turns, victory is your goal, ",
    "Racing is in your blood, the track is your canvas, ",
    "Accelerate towards greatness, brake for nothing, ",
    "From checkpoint to podium, your journey shines, ",
    "Your wheels carve a path to triumph, ",
    "Rev your engine, ignite your ambition, ",
    "Steer towards success, with every corner conquered, ",
    "Racing is your canvas, and speed is your art, ",
    "From start line to finish line, you excel, ",
    "Roads are your playground, victory is your trophy, ",
    "Navigate the asphalt like a virtuoso, ",
    "Speed is your ally, determination your fuel, ",
    "Turn every challenge into a victory lap, ",
    "Master the turns, master the game, ",
    "Carve your legacy on the track, ",
    "Embrace the adrenaline, conquer the road, ",
    "Fuel your passion for speed, cross the finish line with pride, ",
    "Accelerate towards dreams, brake for nothing less, ",
    "From racetrack to winner's circle, you shine, ",
    "Every challenge is a checkpoint on your road to glory, ",
    "Unleash horsepower, unleash victory, ",
    "Your drive propels you forward, your passion fuels your journey, ",
    "Racing is your language, victory is your story, ",
    "From throttle to triumph, you dominate, ",
    "Life's a race, and you're setting the pace, ",
    "Navigate the twists with precision, cross the finish line in triumph, ",
    "Steer your destiny, throttle your ambition, ",
    "Speed, strategy, and success are your allies, ",
    "From lap to victory lap, you excel, ",
    "Navigate the circuit with finesse, claim your victory, ",
    "Roads are your playground, speed is your anthem, ",
    "From race start to podium, your journey is legendary, ",
    "Conquer the track, leave your mark in the dust, ",
    "Your drive is unwavering, your finish line is victory, ",
    "Speed is your game, victory is your destination, ",
    "Master the track, master the thrill, ",
    "Rev your engine, ignite your success, ",
    "Navigate the asphalt with finesse, claim your triumph, ",
    "Accelerate towards your dreams, brake for nothing less, ",
    "From speedway to champion's circle, you reign, ",
    "Racing is your passion, victory is your reward, ",
    "From pedal to medal, you're the star, ",
    "Ride with the wind, conquer the frontier, ",
    "Every challenge is a chance to forge your legacy, ",
    "Saddle up, partner, adventure awaits, ",
    "From the dusty trails to the wild frontiers, you're the outlaw with heart, ",
    "Embrace the wilderness, tame the wild, ",
    "Unleash your inner cowboy, the West is your canvas, ",
    "Roam the open range, leave your mark on history, ",
    "From bullets to bounty, your journey is legendary, ",
    "Every sunset is a new dawn in the wild, ",
    "Master the art of survival, become the legend, ",
    "In the heart of the Wild West, you're the one to watch, ",
    "Gun in hand, spirit unbound, you ride with purpose, ",
    "Conquer the untamed, your story unfolds in the wild, ",
    "Ride towards your dreams, leave no trail unexplored, ",
    "From showdowns to standoffs, you define the law of the land, ",
    "Navigate the desolate landscapes, write your saga, ",
    "Trailblazing spirit, wild heart, you're the cowboy with a vision, ",
    "Embrace the journey, embrace the wild, ",
    "Live by the code of the West, ride with honor, ",
    "From campfires to campfire tales, your story burns bright, ",
    "Rise and shine, outlaw of the dawn, ",
    "Master the horse, master the hunt, master your destiny, ",
    "Saddle up, face the challenges, and emerge victorious, ",
    "From the heartland to the frontier, your adventure knows no bounds, ",
    "Ride through adversity, emerge as a legend, ",
    "Navigate the trails, face your destiny, ",
    "Roam the vast landscapes, your journey is your masterpiece, ",
    "Unleash your gunslinger prowess, become the law's nightmare, ",
    "Embrace the wilderness, write your tale, ",
    "From horseback to heroics, you shape the fate of the Wild West, ",
    "Trailblazing spirit, unwavering courage, you're the cowboy with a mission, ",
    "From cattle rustlers to legends, you're the outlaw to remember, ",
    "Conquer the challenges, conquer the Wild West, ",
    "Live by the gun, live by the code, live your adventure, ",
    "Ride the trails of destiny, embrace your outlaw heart, ",
    "Navigate the unforgiving terrain, become the legend you were born to be, ",
    "From bullets to bravery, you're the gunslinger with a purpose, ",
    "Roam with purpose, every sunrise is a new chapter, ",
    "Embrace the thrill of the Wild West, where your legacy is written, ",
    "Ride against the odds, emerge as the ultimate gunslinger, ",
    "Master the art of the quick draw, master your path, ",
    "Saddle up and ride towards your epic destiny, ",
    "From campfires to showdowns, your tale unfolds in the wild, ",
    "Rise with the dawn, gunslinger of the day, ",
    "Navigate the treacherous trails, emerge as the Wild West legend, ",
    "Embrace the unknown, embrace your destiny, ",
    "From saloons to standoffs, your journey is your triumph, ",
    "Trailblazing spirit, unbridled courage, you're the cowboy with a purpose, ",
    "Ride into the fray, become the outlaw hero, ",
    "Conquer the frontier, embrace your legend, ",
    "Live by your own rules, your journey is your story, ",
    "Ride with the sun, rise above the challenges, ",
    "Navigate the chaos, find your path in the Wild West, ",
    "Explore the world, write your own adventure, ",
    "From city lights to starry nights, the world is your canvas, ",
    "Unleash your wanderlust, embrace the journey, ",
    "Discover new horizons, leave footprints across the globe, ",
    "Every destination is a chapter in your travel story, ",
    "Roam the earth, capture memories, leave your mark, ",
    "Embrace the unknown, embrace the world, ",
    "Unveil the beauty of every corner, become the ultimate explorer, ",
    "Navigate through cultures, weave a tapestry of experiences, ",
    "Roam with purpose, every journey shapes your story, ",
    "From roads less traveled to iconic landmarks, you're the wanderer, ",
    "Embrace the adventure, embrace the globe, ",
    "Unleash your inner nomad, the world is your playground, ",
    "From sunrise to sunset, your journey unfolds with every step, ",
    "Explore the unknown, discover your passion, ",
    "Navigate the world's wonders, your journey is your masterpiece, ",
    "Roam with a curious heart, unveil the world's secrets, ",
    "Embrace diversity, embrace the world, ",
    "From mountains to oceans, your journey knows no bounds, ",
    "Unveil the beauty of cultures, become the global citizen, ",
    "Navigate through landscapes, create memories that last, ",
    "Roam the world's stage, leave behind stories to share, ",
    "Embrace the thrill of exploration, where every moment is a treasure, ",
    "Unleash your adventurous spirit, let your journey define you, ",
    "From local flavors to foreign shores, you're the traveler with a vision, ",
    "Navigate the map, let your wanderlust guide the way, ",
    "Roam with an open heart, collect moments, not just souvenirs, ",
    "Embrace the road less traveled, embrace the world's mysteries, ",
    "Unveil the hidden gems, create memories that last a lifetime, ",
    "Explore the wonders of the world, become the ultimate wanderer, ",
    "Navigate through experiences, create a storybook of memories, ",
    "Roam freely, live fully, embrace the world's beauty, ",
    "Embrace the magic of discovery, let the world be your inspiration, ",
    "Unleash your explorer's spirit, the world is your playground, ",
    "From cultures to cuisines, you're the seeker of enriching experiences, ",
    "Navigate the globe, write your own global adventure, ",
    "Roam with purpose, discover the world's mysteries, ",
    "Embrace diversity, embrace unity, embrace the world, ",
    "Unveil the stories of places, become the storyteller of your journey, ",
    "Explore the tapestry of cultures, leave your footprints in the sand, ",
    "Navigate with an open heart, every destination leaves an impression, ",
    "Roam with curiosity, unlock the world's treasures, ",
    "Embrace the excitement of the unknown, become the global discoverer, ",
    "Unleash your traveler's heart, let the world be your guide, ",
    "From wonders to wanderlust, you're the globetrotter with dreams, ",
    "Navigate through landscapes and languages, create a mosaic of memories, ",
    "Roam with wonder, every journey is a chance to rewrite your story, ",
    "Embrace the beauty of cultures, embrace the beauty of the world, ",
    "Unveil the breathtaking landscapes, become the world's observer, ",
    "Explore the intersections of cultures, become the bridge between worlds, ",
    "Navigate through time zones and continents, leave your legacy on the map, ",
    "Roam with purpose, embrace the thrill of the unknown, ",
    "Embrace the global tapestry, you're the traveler with a heart full of wanderlust, ",
    "Unleash your inner adventurer, let the world be your compass, ",
    "Embrace the joy of cartoons, let laughter guide your day!",
    "Step into a world of animated wonder, where imagination knows no bounds.",
    "Find inspiration in the whimsical worlds of cartoons, where anything is possible.",
    "Let the colorful characters and stories of cartoons ignite your creativity!",
    "Unlock your inner child with the magic of cartoons, where dreams come to life.",
    "Discover the artistry behind every frame of your favorite cartoons, a masterpiece of animation.",
    "Embrace the nostalgia of cherished cartoons, a journey to the past that brings smiles.",
    "From classic to modern, cartoons are a reminder that fantasy knows no limits.",
    "Laugh with the characters, learn from their adventures, and carry their spirit with you.",
    "Cartoons are more than entertainment, they're a source of inspiration and joy!",
    "Immerse yourself in the stories of cartoons, where life lessons are painted with humor.",
    "Let the charm of cartoons light up your day, a beacon of positivity and fun.",
    "Explore the animated universes that capture your heart, where magic is never far away.",
    "From Saturday morning smiles to animated classics, cartoons are a treasure trove of happiness.",
    "Cartoons teach us that even the most unconventional ideas can lead to wonderful adventures.",
    "Embrace the creativity of cartoons, a canvas where imagination takes center stage.",
    "From laughter to lessons, cartoons weave stories that resonate with every age.",
    "Cartoons remind us that every challenge can be overcome with a bit of humor and heart.",
    "Step into the shoes of your favorite cartoon characters and let their courage inspire you.",
    "Behind every cartoon lies a team of artists, creators, and dreamers who bring stories to life.",
    "Discover the messages of kindness, friendship, and courage that cartoons convey.",
    "Embrace the whimsy and wonder of the cartoon world, where the impossible becomes possible.",
    "Let the characters of cartoons remind you that even in tough times, smiles can be found.",
    "Cartoons are a reminder to keep dreaming, keep believing, and keep chasing adventures.",
    "Unleash your creativity with the spirit of cartoons, where every idea is worth exploring.",
    "From the first frame to the last, cartoons are a journey into the heart of imagination.",
    "Embrace the laughter and lessons that cartoons offer, a timeless source of inspiration.",
    "Cartoons teach us that the journey is just as important as the destination.",
    "Step into a world of animated artistry, where stories come alive with every brushstroke.",
    "Let the magic of cartoons remind you that life is an adventure waiting to be explored.",
    "Cartoons capture the essence of childhood wonder, a reminder to never stop dreaming.",
    "Embrace the characters who taught you about friendship, love, and the power of imagination.",
    "From pencil sketches to digital wonders, cartoons are a testament to human creativity.",
    "Let the whimsical worlds of cartoons be your sanctuary of joy and inspiration.",
    "Cartoons remind us that sometimes a little laughter is all we need to brighten our day.",
    "Discover the charm of cartoons, where stories are told through vibrant visuals and heartwarming tales.",
    "Embrace the artistry and storytelling of cartoons, a tapestry woven with creativity.",
    "Cartoons are a celebration of diversity, a reminder that every character brings something unique.",
    "Step into the shoes of your favorite cartoon heroes, and let their bravery inspire your journey.",
    "Let the colors and characters of cartoons ignite your imagination and light up your path.",
    "Cartoons transport us to magical worlds, where fantasy and reality blur into joy.",
    "Embrace the lessons of courage, perseverance, and friendship that cartoons impart.",
    "From ink and paper to pixels and screens, cartoons are a testament to the evolution of art.",
    "Let the characters of cartoons be your companions in times of both joy and challenge.",
    "Cartoons remind us that even in the toughest moments, a smile can make a difference.",
    "Discover the hidden treasures of wisdom and wit that lie within the stories of cartoons.",
    "Embrace the playfulness of cartoons, where silliness is a remedy for a heavy heart.",
    "Cartoons inspire us to think beyond the ordinary, and let our imaginations run wild.",
    "Step into the animated world with an open heart, and let its magic fill your life.",
    "Let the lessons from cartoon adventures guide your steps, and the humor lighten your load.",
    "Cartoons are a reminder that no matter the circumstances, a little laughter can go a long way.",
    "Embrace the childlike wonder that cartoons bring, and let it infuse your world with joy.",
    "Embrace anime's boundless creativity!",
    "Find strength in anime's stories.",
    "Let anime's art inspire you!",
    "Connect hearts through anime's tales.",
    "Cherish anime's colorful journeys!",
    "Discover worlds within anime.",
    "Anime fuels dreams and passions.",
    "Anime sparks endless imagination.",
    "Let anime's spirit guide you.",
    "Anime's lessons resonate deeply.",
    "Empower dreams with anime's magic.",
    "Anime celebrates uniqueness within us.",
    "Anime's essence, life's inspiration.",
    "Anime's heart, soul's kinship.",
    "Anime's colors paint inspiration.",
    "Anime's artistry speaks volumes.",
    "Anime's tales ignite determination.",
    "Anime nurtures hearts, fuels aspirations.",
    "Embrace anime's lessons, wisdom follows.",
    "Anime characters, mirrors to souls.",
    "Anime's emotions, a universal language.",
    "Let anime's stories uplift spirits.",
    "Anime's journeys mirror life's adventures.",
    "Anime's stories, life's reflection.",
    "Anime inspires, hearts resonate.",
    "Anime's heroes, courage personified.",
    "Let anime's light guide you.",
    "Anime's courage, our own strength.",
    "Anime's journeys, ours to embark.",
    "Anime's magic fuels life's dreams.",
    "Let anime's melodies soothe spirits.",
    "Anime's bonds, life's connections.",
    "Anime empowers, hearts alight.",
    "Anime's lessons, growth's whispers.",
    "Anime's dreams fuel real aspirations.",
    "Embrace anime's tales, find wisdom.",
    "Anime's energy, ignites passions.",
    "Anime's tales, life's guideposts.",
    "Anime's hope, hearts' sustenance.",
    "Anime's colors, life's vibrancy.",
    "Embrace anime's world, explore possibilities.",
    "Anime's lessons, life's compass.",
    "Anime's tales, lessons abound.",
    "Anime's magic, dreams take flight.",
    "Embrace anime's heart, inspire life.",
    "Anime's journeys, lessons for us.",
    "Anime's dreams, ours to chase.",
    "Anime's bonds, hearts united.",
    "Embrace anime's tales, ignite dreams.",
    "Anime's journey, our own adventure.",
    "Anime's courage, mirror our own.",
    "Let anime's stories light paths.",
    "Anime's essence, life's inspiration.",
    "Savor every flavor adventure!",
    "Indulge in culinary journeys.",
    "Let food awaken joy within.",
    "Feast on life's delicious moments.",
    "Embrace each dish with delight.",
    "Discover joy in every bite.",
    "Food: a taste of happiness.",
    "Eat well, live vibrantly.",
    "Cooking: a love language spoken.",
    "Find comfort in culinary creations.",
    "Every meal, a memory made.",
    "Food connects hearts and tastes.",
    "Let flavors dance on your tongue.",
    "Food: the art of nourishment.",
    "Celebrate life, one meal at a time.",
    "Savor, relish, repeat joyfully.",
    "Explore cultures through cuisine.",
    "Food fuels the body and soul.",
    "Embrace culinary curiosity daily.",
    "Foodies find joy in bites.",
    "Create, share, and savor memories.",
    "Cooking: a canvas for creativity.",
    "Food lovers, unite with flavors!",
    "Food is love, tastefully shared.",
    "Every plate, a masterpiece curated.",
    "Indulge in culinary storytelling.",
    "Let food be your daily adventure.",
    "Food: the ultimate comfort embrace.",
    "Cooking: a journey to savor.",
    "Food connects us, no boundaries.",
    "Discover joy in culinary artistry.",
    "Embrace flavors, ignite passion.",
    "Food: a symphony for senses.",
    "Savor every bite like poetry.",
    "Feast on life's abundant flavors.",
    "Eat, love, share, repeat.",
    "Food: a journey of discovery.",
    "Every meal, a celebration shared.",
    "Food unites hearts and tastes.",
    "Let flavors paint life's palate.",
    "Food is life's flavorful companion.",
    "Cook with love, taste the magic.",
    "Food: a tapestry of cultures.",
    "Indulge, relish, nourish deeply.",
    "Explore culinary worlds with delight.",
    "Food fuels dreams, ignites joy.",
    "Embrace taste adventures daily.",
    "Food: an art form on plates.",
    "Cooking: the joy of creation.",
    "Food brings smiles, unites souls.",
    "Savor the moments, taste life.",
    "Discover love through food's essence.",
    "Embrace culinary treasures daily.",
    "Food: a journey of senses.",
    "Eat with gratitude, love flavors.",
    "Excellence is your academic signature.",
    "Topping the charts, reaching for stars.",
    "Knowledge: your stairway to success.",
    "Consistency fuels your academic rise.",
    "Every challenge, a stepping stone.",
    "Scholarship: your road to greatness.",
    "Strive for greatness, reach for mastery.",
    "Success is your favorite subject.",
    "Toppers lead with determination.",
    "Learning today, leading tomorrow.",
    "Curiosity sparks your academic journey.",
    "Toppers excel with passion.",
    "Knowledge blooms in your footsteps.",
    "Dedication: your academic compass.",
    "Leading the way through dedication.",
    "Every effort propels your ascent.",
    "Toppers illuminate the academic path.",
    "Success is your classroom companion.",
    "Achievement, your constant companion.",
    "Champions of learning, future leaders.",
    "Diligence fuels your academic flight.",
    "Leading with intellect, guiding with heart.",
    "Toppers thrive on learning adventures.",
    "Wisdom shines through your efforts.",
    "Leading minds, shaping tomorrows.",
    "Toppers pioneer new heights.",
    "Learning: your secret to triumph.",
    "Eyes set on the pinnacle.",
    "Champions of study, life, and beyond.",
    "Inquisitive minds, infinite horizons.",
    "Success is your study partner.",
    "Toppers inspire others to rise.",
    "Leading through dedication, not chance.",
    "Toppers mold futures with knowledge.",
    "Learning today, leading the world.",
    "Perseverance paves your academic journey.",
    "Champion of education, a beacon.",
    "Inquisitive spirits, academic leaders.",
    "Success dances to your academic rhythm.",
    "Toppers are sculptors of their fate.",
    "Toppers: captains of the academic ship.",
    "Leading minds, creating legacies.",
    "Success writes your academic story.",
    "Toppers ascend through hard work.",
    "Learning ignites your academic flame.",
    "Leading by example, igniting minds.",
    "Toppers chase dreams with purpose.",
    "Success loves to accompany you.",
    "Toppers inspire, innovate, influence.",
    "Learning: your ladder to success.",
    "Hope shines brighter than circumstances.",
    "Strength within, regardless of wealth.",
    "Resilience blooms in adversity.",
    "Dreams flourish beyond financial boundaries.",
    "Potential thrives, despite the wallet.",
    "Empowerment transcends material riches.",
    "Character defines wealth within.",
    "Fortitude fuels your journey.",
    "Circumstances can't define your worth.",
    "Value lies beyond material possessions.",
    "Rise above, conquer your path.",
    "Adversity shapes remarkable stories.",
    "Strength found in humble beginnings.",
    "Dream big, persevere stronger.",
    "Endurance transforms limitations into triumphs.",
    "Empowerment grows from within.",
    "Determination defies financial constraints.",
    "Potential thrives beyond dollar signs.",
    "Resilience outshines temporary struggles.",
    "Powerful spirit, infinite possibilities.",
    "Dreams are boundless, not bank-dependent.",
    "Richness of spirit knows no bounds.",
    "Challenges: stepping stones to success.",
    "Success knows no financial boundaries.",
    "Rise with ambition, irrespective of resources.",
    "Inner wealth trumps outer limitations.",
    "Strength resides in your heart.",
    "Adversity breeds remarkable strength.",
    "Triumphs arise from humble beginnings.",
    "Potential blooms, unfazed by circumstance.",
    "Powerful mindset, unstoppable journey.",
    "Empowerment radiates from within.",
    "Dreams know no monetary limits.",
    "Character shines through life's challenges.",
    "Resilience illuminates the darkest paths.",
    "Passion prevails, wealth or not.",
    "Strength builds, despite financial storms.",
    "Endurance: your bridge to triumph.",
    "Dreams unfurl, regardless of wallet.",
    "Empowerment knows no price tag.",
    "Triumphs born from persistence.",
    "Challenges: the seeds of greatness.",
    "Character shapes paths to success.",
    "Resilience conquers even the toughest odds.",
    "Potential is boundless, rich or poor.",
    "Strength within, a guiding light.",
    "Adversity fuels your unique journey.",
    "Dreams are yours to claim.",
    "Empowerment blooms within your spirit.",
    "Triumph knows no financial barriers.",
    "Strength isn't confined by resources.",
    "Passion fuels progress, not wealth.",
    "Resilience shapes a powerful physique.",
    "Dreams sculpted through determination.",
    "Potential grows regardless of budget.",
    "Empowerment blooms in sweat.",
    "Character fuels gains beyond finances.",
    "Fortitude strengthens your journey.",
    "Muscles built from unwavering will.",
    "Transformation defies financial limits.",
    "Adversity molds remarkable champions.",
    "Dream big, sculpt stronger.",
    "Inner strength conquers all obstacles.",
    "Triumphs born from humble beginnings.",
    "Power surges from within.",
    "Dreams lifted by sheer willpower.",
    "Resilience crafts a powerful physique.",
    "Empowerment thrives in your dedication.",
    "Potential unleashed regardless of cost.",
    "Strength is built on relentless effort.",
    "Grit knows no financial restrictions.",
    "Challenges: stepping stones to muscle.",
    "Success thrives amidst adversity.",
    "Rise with passion, whatever your means.",
    "Inner power outshines external limits.",
    "Adversity forges a warrior spirit.",
    "Transformation transcends financial boundaries.",
    "Muscles reflect your inner strength.",
    "Triumph born from relentless commitment.",
    "Empowerment comes from within.",
    "Dreams are built, not bought.",
    "Character ignites the fire within.",
    "Resilience shapes an unbeatable physique.",
    "Strength rises above financial hurdles.",
    "Progress radiates from determination.",
    "Gains know no monetary barriers.",
    "Endurance: forging a muscular future.",
    "Dreams sculpted by inner resolve.",
    "Empowerment is within your reach.",
    "Triumphs achieved, despite the odds.",
    "Challenges sculpt the best versions.",
    "Character fuels a sculpted destiny.",
    "Resilience carves a warrior's path.",
    "Potential knows no budget limits.",
    "Strength is built through dedication.",
    "Adversity transforms into muscle.",
    "Transformation thrives in dedication.",
    "Dreams crafted from sweat and heart.",
    "Empowerment is your personal journey.",
    "Triumph carved from persistence."
  ];
  
  function getMotivationalPhrase() {
    const now = new Date();
    const dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 86400000);
    const selectedPhraseIndex = dayOfYear % motivationalPhrases.length;
    return motivationalPhrases[selectedPhraseIndex];
  }

  let currentPhraseIndex;

// function getRandomQuoteIndex() {
//   return Math.floor(Math.random() * motivationalPhrases.length);
// }

function updateMotivationalPhrase() {
  const now = new Date();
  const dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 86400000);

  if (!currentPhraseIndex || now.getHours() === 0) {
    currentPhraseIndex = dayOfYear % motivationalPhrases.length;
    localStorage.setItem('currentPhraseIndex', currentPhraseIndex); // Store the index when the day changes
  }

  const quoteSpan = document.getElementById('quote');
  const motivationalPhrase = getMotivationalPhrase();
  quoteSpan.textContent = motivationalPhrase;
}

// function changeQuoteManually() {
//   currentPhraseIndex = (currentPhraseIndex + 1) % motivationalPhrases.length;
//   localStorage.setItem('currentPhraseIndex', currentPhraseIndex); // Store the index when manually changed
//   quoteSpan.textContent = motivationalPhrases[currentPhraseIndex];
// }

// Call the function initially to set the phrase on page load
const storedIndex = localStorage.getItem('currentPhraseIndex');
currentPhraseIndex = storedIndex !== null ? parseInt(storedIndex, 10) : 0;
localStorage.setItem('currentPhraseIndex', currentPhraseIndex); // Store the index for future refreshes
const quoteSpan = document.getElementById('quote');
const initialMotivationalPhrase = getMotivationalPhrase();
quoteSpan.textContent = initialMotivationalPhrase;

// Call the function every minute to check if it's 12:00 AM
setInterval(updateMotivationalPhrase, 60000);

// const changeQuoteButton = document.getElementById('change-quote-button');
// changeQuoteButton.addEventListener('click', changeQuoteManually);